export const channelsPlaylistIds = {
    VANAS_CHANNEL_UPLOADS_ID: 'UUrcg40cuUt7QZFUd-cOywPw',
    DISNEY_CHANNEL_UPLOADS_ID: 'UUuaFvcY4MhZY3U43mMt1dYQ',
    XBOX_CHANNEL_UPLOADS_ID: 'UUjBp_7RuDBUYbd1LegWEJ8g',
    AARDMAN_CHANNEL_UPLOADS_ID: 'UUNtOgTAORZDgXE2U6XJAFYQ'
};

export const channeIds = {
    VANAS_CHANNEL_ID: 'UCrcg40cuUt7QZFUd-cOywPw',
    DISNEY_CHANNEL_ID: 'UCuaFvcY4MhZY3U43mMt1dYQ',
    XBOX_CHANNEL_ID: 'UCjBp_7RuDBUYbd1LegWEJ8g',
    AARDMAN_CHANNEL_ID: 'UCNtOgTAORZDgXE2U6XJAFYQ'
};

