export const channelsPlaylistIds = {
    VANAS_CHANNEL_UPLOADS_ID: 'UUrcg40cuUt7QZFUd-cOywPw',
    WALT_DISNEY_ANIMATION_CHANNEL_UPLOADS_ID: 'UU_976xMxPgzIa290Hqtk-9g',
    XBOX_CHANNEL_UPLOADS_ID: 'UUjBp_7RuDBUYbd1LegWEJ8g',
    AARDMAN_CHANNEL_UPLOADS_ID: 'UUNtOgTAORZDgXE2U6XJAFYQ',
    ILLUMINATION_FILMS_CHANNEL_UPLOADS_ID: 'UUq7OHvWO6Z3u-LztFdrcU-g',
    SONY_PICTURES_ANIMATION_CHANNEL_UPLOADS_ID: 'UUnLuLSV-Oi0ctqjxGgxFlmg',
    FORTNITE_CHANNEL_UPLOADS_ID: 'UUlG8odDC8TS6Zpqk9CGVQiQ',
    PIXAR_CHANNEL_UPLOADS_ID: 'UU_IRYSp4auq7hKLvziWVH6w',
    MAYA_LEARNING_CHANNEL_UPLOADS_ID: 'UUHmAXsicpLK2EHMZo5_BtDA',
};


// We only need the channel Ids to retrieve the upload Id. It's a good idea to keep them in this file to organize the project.

export const channeIds = {
    VANAS_CHANNEL_ID: 'UCrcg40cuUt7QZFUd-cOywPw',
    WALT_DISNEY_ANIMATION_CHANNEL_ID: 'UC_976xMxPgzIa290Hqtk-9g',
    XBOX_CHANNEL_ID: 'UCjBp_7RuDBUYbd1LegWEJ8g',
    AARDMAN_CHANNEL_ID: 'UCNtOgTAORZDgXE2U6XJAFYQ',
    ILLUMINATION_FILMS_CHANNEL_ID: 'UCq7OHvWO6Z3u-LztFdrcU-g',
    SONY_PICTURES_ANIMATION_CHANNEL_ID: 'UCnLuLSV-Oi0ctqjxGgxFlmg',
    FORTNITE_CHANNEL_ID: 'UClG8odDC8TS6Zpqk9CGVQiQ',
    PIXAR_CHANNEL_ID: 'UC_IRYSp4auq7hKLvziWVH6w',
    MAYA_LEARNING_CHANNEL_ID: 'UCHmAXsicpLK2EHMZo5_BtDA',
};

